export const INIT_STATE='INIT_STATE'
export const USER_LOGIN='USER_LOGIN'
export const USER_LOGOUT='USER_LOGOUT'
export const MESSAGE_ADD='MESSAGE_ADD'
export const MESSAGE_INIT='MESSAGE_INIT'
export const MESSAGE_EMPTY='MESSAGE_EMPTY'
// export const MESSAGE_MINUS='MESSAGE_MINUS'

